message(STATUS "Using clang toolchain")
set(CMAKE_SYSTEM_PROCESSOR ${OS_ARCH})
set(triple x86_64-pc-linux-elf)
set(CMAKE_SYSROOT ${TOOLCHAIN_SYSROOT})
set(CMAKE_FIND_ROOT_PATH  ${TOOLCHAIN_SYSROOT})
set(CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES 
${TOOLCHAIN_SYSROOT}/include/c++/${TOOLCHAIN_CXX_VERSION}/${TOOLCHAIN_TRIPLET}
${TOOLCHAIN_SYSROOT}/include/c++/${TOOLCHAIN_CXX_VERSION}/
)
set(CMAKE_C_COMPILER_TARGET ${triple})
set(CMAKE_CXX_COMPILER_TARGET ${triple})
set(CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN ${CLANG_TOOLCHAIN_SYSROOT})
set(CMAKE_C_COMPILER_EXTERNAL_TOOLCHAIN ${CLANG_TOOLCHAIN_SYSROOT})
string(APPEND CMAKE_EXE_LINKER_FLAGS " -fuse-ld=lld")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
